version: "3.7"

services:
  # https://github.com/localstack/localstack
  localstack:
    container_name: localstack
    image: localstack/localstack-full:latest
    hostname: localstack
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      #- HOSTNAME=aws
      - DEFAULT_REGION=us-west-2
      #- SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,es,firehose,iam,kinesis,lambda,route53,redshift,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts
      # required but not directly used: iam,cloudformation,sts
      - SERVICES=apigateway,lambda,s3,sqs,secretsmanager,iam,cloudformation,sts
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      #- LAMBDA_DOCKER_NETWORK=
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      # DOCKER_CMD="sudo docker"
      # Use these if mounting from local drive in serverless.yml
      # - HOST_TMP_FOLDER=${PWD}/.localstack      
      # - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d

#   # TODO make external
#   # https://zgadzaj.com/development/docker/docker-compose/containers/mongodb
#   # https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
#   mongodb_container:
#     image: mongo:latest
#     hostname: mongo
#     ports:
#         - 27017:27017
#     environment:
#         MONGO_INITDB_ROOT_USERNAME: root
#         MONGO_INITDB_ROOT_PASSWORD: root
#     volumes:
#         - ./data/mongo/:/data/db/      
# networks:
#    default:
#       external:
#          name: shared