# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/?rd=true
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: node-101
# app and org for use with dashboard.serverless.com
# app: none-101
# org: tec.org

# https://medium.com/manomano-tech/using-serverless-framework-localstack-to-test-your-aws-applications-locally-17748ffe6755
# https://www.serverless.com/plugins/serverless-localstack
# https://www.serverless.com/plugins/serverless-plugin-typescript
# https://www.serverless.com/plugins/serverless-plugin-include-dependencies
# https://www.serverless.com/plugins/serverless-plugin-common-excludes
plugins:
  - serverless-localstack
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566
    autostart: true  # optional - start LocalStack in Docker on Serverless deploy
    lambda:
      # Enable this flag to improve performance
      mountCode: false
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: False

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  
  stage: local
  region: us-west-2

package:
  excludeDevDependencies: False
  #include:
  #  - src/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  echo:
    handler: src/functions/handler.echo
    runtime: nodejs12.x
    timeout: 20
    memorySize: 256
    events:
      - http:
          path: /echo
          method: get
          cors: true          
  record:
    handler: src/functions/handler.record
    runtime: nodejs12.x
    timeout: 20
    memorySize: 256
    events:
      - sqs:
          arn: arn:aws:sqs:us-west-2:000000000000:click
          batchSize: 10
          enabled: true