cookie: "tag-your-it"
aws:
  localstack: false
  region: "us-west-2"
  sqs:
    queue: "node-101-click"
  s3:
    bucket: "node-101-archive"
db:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  database: 'test'
  synchronize: true
  logging: true
  username: 'root'
  password: 'root'
encryption:
  # TODO move to secrets
  secret: 'donttellanyone'  