cookie: "tag-your-it"
aws:
  localstack: true
  endpoint: "http://localhost:4566/"
  region: "us-west-2"
  sqs:
    queue: "node-101-click"
  s3:
    bucket: "node-101-archive"
db:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  database: 'test'
  synchronize: true
  logging: true
  username: 'test'
  password: 'test'
encryption:
  config: 'dev/node-101/encryption'