aws:
  region: "us-west-2"
sqs:
  queue: 'node-101-click'
s3:
  bucket: 'node-101-archive'

# MysqlConnectionOptions
# https://typeorm-doc.exceptionfound.com/interfaces/mysqlconnectionoptions.html
db:
  type: 'mysql'
  host: 'db'
  port: 3306
  database: 'test'
  synchronize: true
  logging: true
  username: 'test'
  password: 'test'
  entities: 
    - "src/entity/**/*.ts"